version: 0.0.{build}
configuration: Release
image: Visual Studio 2017
init:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  namespace: Objectivity.Bot.Tests.Stories.Xunit
  cc: opencover
install:
- ps: >-
    choco install codecov
build_script:
- cmd: >-
    dotnet build
test_script:
- cmd: >-
    dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=%cc% /p:CoverletOutput=%appveyor_build_folder%\%cc%\%namespace%.xml

    codecov -f %appveyor_build_folder%\%cc%\%namespace%.xml --flag unittests
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: ZDpU+qPlLxIhcfhYnqYxazI6g9gwt6e086vlBogpXETSL9C7WTbLdaH6rPEOz3v7
  on:
    appveyor_repo_tag: true
  skip_symbols: false