version: 0.0.{build}
configuration: Release
image: Visual Studio 2017
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
init:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
before_build:
- cmd: nuget restore
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true")

    {

    .\Update-Nuspec.ps1 -version "$env:APPVEYOR_REPO_TAG_NAME"

    }
build:
  verbosity: detailed
  publish_nuget: true
  publish_nuget_symbols: true
test:
  assemblies:
    - '**\*.Tests.dll'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  NugetApiKey:
    secure: DIE2y66RzXWvp2Q0wIOLlBTjxILBGeHyyg3pjwWjdVrggzuj9BuMWCdfHFmt9nt2
deploy:
  - provider: NuGet
    api_key: $(NugetApiKey)
    artifact: /.*\.nupkg/
    on:
      appveyor_repo_tag: true
    skip_symbols: false