version: 0.0.{build}
image: Visual Studio 2017
configuration: Release
init:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true")
    {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.split("-")[0])"
    }
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  namespace: Objectivity.Bot.Tests.Stories.Xunit
  cc: opencover
  matrix:
  - package_module: V3
    package_suffix: 
  - package_module: V4
    package_suffix: .V4
install:
- ps: >-
    choco install codecov
build_script:
- ps: >-
    dotnet build ./src
    
    if ($env:APPVEYOR_REPO_TAG -eq "true")
    {
        dotnet pack ./src/$env:package_module/$env:namespace$env:package_suffix --no-build -p:PackageVersion=$env:APPVEYOR_REPO_TAG_NAME
    }
    else
    {
        dotnet pack ./src/$env:package_module/$env:namespace$env:package_suffix --no-build -p:PackageVersion=$env:APPVEYOR_BUILD_VERSION
    }
test_script:
- cmd: >-
    dotnet test ./src /p:CollectCoverage=true /p:CoverletOutputFormat=%cc% /p:CoverletOutput=%appveyor_build_folder%\%cc%\%namespace%%package_suffix%.xml

    codecov -f %appveyor_build_folder%\%cc%\%namespace%%package_suffix%.xml --flag unittests
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: ZDpU+qPlLxIhcfhYnqYxazI6g9gwt6e086vlBogpXETSL9C7WTbLdaH6rPEOz3v7
  on:
    appveyor_repo_tag: true
  skip_symbols: false